### ISSUE TITLE
Whitespace is shown when using a terminal

### ISSUE THREAD

**Issue by pmatulis** [zakharykaplan/nvim-retrail#12]
Thanks for the plugin. It's working well.

However, when I have a neovim terminal open (via plugin [toggleterm](https://github.com/akinsho/toggleterm.nvim)) the retrail plugin highlights whitespace. When I disable the retrail plugin completely the highlighting goes away. I believe my configuration is saying to exclude retrail when I'm using a terminal.

My configuration includes:

``` lua
  buftype = {
    -- Strictly enable only on `include`ed buftypes. When false, only disabled
    -- on an `exclude`ed buftype.
    strict = false,
    -- Included filetype list. Overrides `include` list.
    include = {},
    -- Excluded filetype list.
    exclude = {
      "help",
      "nofile",
      "prompt",
      "quickfix",
      "terminal",
    }
  },
```

**Comment by kaplanz** [comment]
Interesting... I can't seem to reproduce this issue on my end. Could you share the values of the `buftype` and `filetype` options within a terminal window that has this issue?

Alternatively, does appending `"toggleterm"` to the `filetype.exclude` option fix it?

**Comment by pmatulis** [comment]
Update: when I return to neovim (terminal stays alive) and toggle back to the terminal the symptoms are not present. It's only during the initial viewing of the terminal that they appear.

> Alternatively, does appending "toggleterm" to the filetype.exclude option fix it?

Yes! :hugs:

**Comment by azzamsa** [comment]
@kaplanz  should I add "toggleterm" as default? I am okay with a PR.

**Comment by kaplanz** [comment]
Sure! Make sure to update the README as well (like in #563e9a9).

**Comment by azzamsa** [comment]
@kaplanz I made a PR https://github.com/kaplanz/retrail.nvim/pull/13 :)
