### ISSUE TITLE
Error in combination with gv.vim

### ISSUE THREAD

**Issue by pogopaule** [zakharykaplan/nvim-retrail#2]
I noticed some errors I get in combination with some older vim plugins. For example `:GV` ([gv.vim](https://github.com/junegunn/gv.vim)) gives me:

```
Error detected while processing BufWinEnter Autocommands for "*":
Error executing lua callback: Vim:E803: ID not found: 5
stack traceback:
        [C]: in function 'matchdelete'
        ...site/pack/packer/start/nvim-retrail/lua/retrail/init.lua:88: in function 'matchdelete'
```

**Comment by kaplanz** [comment]
It seems this issue is caused by a bug in the logic tracking the existing matches for each window.

The fix should be straightforward, but let me do more testing before I commit.

**Comment by kaplanz** [comment]
Fixed. Let me know if the problem persists for you, otherwise please close this issue.

**Comment by pogopaule** [comment]
Cool, thanks for the quick fix. Works now! :+1:
